Parcial_Final/Appportal/Appportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Webinicio.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Parcial_Final/Appportal/Webinicio/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('producto-detalle/<int:producto_id>/', views.producto_detalle, name='producto-detalle'),
    path('profesionales/', views.profesionales_view, name='profesionales'),
    path('no-profesionales/', views.no_profesional_view, name='no_profesionales'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('perfil/', views.perfil, name='perfil'),
    path('ver-carrito/', views.ver_carrito, name='ver_carrito'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registro/', views.registro, name='registro'),
]

Parcial_Final/Appportal/Webinicio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ProductoImagen(models.Model):
  producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
  imagen = models.ImageField(upload_to='producto_imagenes/')
  
class Producto(models.Model):
  nombre = models.CharField(max_length=255)
  precio = models.DecimalField(max_digits=10, decimal_places=2)
  imagen = models.ImageField(upload_to="productos", null=True)
  categoria = models.CharField(max_length=255, choices=[('profesional', 'Profesional'), ('no_profesional', 'No profesional')])
  descripcion = models.TextField(blank=True, null=True)
  
  def __str__(self):
    return self.nombre
  
  def get_imagen_url(self):
    return self.imagen.url if self.imagen else ''

class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)
    
    from django.db import models

class Banner(models.Model):
    nombre = models.CharField(max_length=255)
    imagen = models.ImageField(upload_to='banners/')

    def __str__(self):
        return self.nombre

Parcial_Final/Appportal/Webinicio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistroForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Ingrese un correo válido')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

Parcial_Final/Appportal/Webinicio/views.py
from .models import Producto, Carrito, Banner
from .forms import RegistroForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout

def index(request):
    productos = Producto.objects.all()
    banners = Banner.objects.all()
    return render(request, 'index.html', {'productos': productos, 'banners': banners})

def producto_detalle(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    imagenes = producto.productoimagen_set.all()
    return render(request, 'producto_detalle.html', {'producto': producto, 'imagenes': imagenes})

def profesionales_view(request):
    productos_profesionales = Producto.objects.filter(categoria='profesional')
    return render(request, 'profesional.html', {'productos': productos_profesionales})

def no_profesional_view(request):
    productos_no_profesionales = Producto.objects.filter(categoria='no_profesional')
    return render(request, 'no_profesional.html', {'productos': productos_no_profesionales})

def iniciar_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

@login_required
def perfil(request):
    usuario = request.user
    return render(request, 'perfil.html', {'usuario': usuario})

def cerrar_sesion(request):
    logout(request)
    return redirect('index')

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('login')
    else:
        form = RegistroForm()
    return render(request, 'registro.html', {'form': form})

def ver_carrito(request):
    productos = Producto.objects.all()
    return render(request, 'carrito.html', {'productos': productos})

Parcial_Final/Appportal/Webinicio/templates/carrito.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="{% static 'img/logo_main.png' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  <title>Carrito de Compras</title>
</head>
<body>
  <header class="container">
    <div class="buttons">
    </div>
    <div class="product-header">
    <nav>
      <ul>
        <a href="{% url 'index' %}" class="botonVerMas">Inicio</a>
        <a href="{% url 'profesionales' %}" class="botonVerMas">Profesionales</a>
        <a href="{% url 'no_profesionales' %}" class="botonVerMas">Estandar</a>
        {% if user.is_authenticated %}
          <a href="{% url 'perfil' %}" class="botonVerMas">Perfil</a>
        {% else %}
          <a href="{% url 'login' %}" class="botonVerMas">Iniciar sesión o Registrarse</a>
        {% endif %}
      </ul>
    </nav>
    <div class="cart-icon" style="position: absolute; top: 10px; right: 40px;">
      <a href="{% url 'ver_carrito' %}" id="cart-link">
        <img href="{% url 'ver_carrito' %}" src="{% static 'img/bolsa_compras.png' %}" alt="Carrito">
        <span id="cart-count">12</span>
      </a>
  </div>
    </div>
    <h1 class="title">Carrito de Compras</h1>
  </header>

  <main class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Precio</th>
        </tr>
      </thead>
      <tbody>
        {% for producto in productos %}
        <tr>
          <td>{{ producto.nombre }}</td>
          <td>${{ producto.precio }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="3"><strong>Total:</strong></td>
          <td><span>$7,065,700.00.</span></td>
        </tr>
      </tbody>
    </table>
  </main>
  <footer class="container">
    <p>Derechos Reservados © Año</p>
  </footer>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="{% static 'img\logo_main.png' %}">
  <link rel="icon" href="{% static 'img\logo_main.png' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script defer src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <title>Audio Evolution</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div style="position: relative;">
    <header class="container">
      <div class="buttons">
        <a href="{% url 'profesionales' %}" class="btn">Profesionales</a>
        <a href="{% url 'no_profesionales' %}" class="btn">Estandar</a>
        {% if user.is_authenticated %}
            <a href="{% url 'perfil' %}" class="btn">Perfil</a>
        {% else %}
            <a href="{% url 'login' %}" class="btn">Iniciar Sesión o Registrarse</a>
        {% endif %}    
        <h1 class="title" style="font-family: Finland;">Audio Evolution</h1>
      </div>
        <div class="cart-icon" style="position: absolute; top: 10px; right: 40px;">
          <a href="{% url 'ver_carrito' %}" id="cart-link">
            <img href="{% url 'ver_carrito' %}" src="{% static 'img/bolsa_compras.png' %}" alt="Carrito">
            <span id="cart-count">12</span>
          </a>
        </div>
    </header>
    <main>
      <div style="width: 100%; left: 0%;" id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for banner in banners %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
          {% endfor %}
        </ol>
        <div class="carousel-inner">
          {% for banner in banners %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img class="d-block mx-auto" style="max-width: 100%; height: auto;"  class="d-block w-100" src="{{ banner.imagen.url }}" alt="{{ banner.nombre }}">
            </div>
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>      
      <section class="products">
        {% for producto in productos %}
          <div class="product">
            <img class="product-image" src="{{ producto.get_imagen_url }}" alt="{{ producto.nombre }}">
            <h2>{{ producto.nombre }}</h2>
            <p>${{ producto.precio }}</p>
            <a class="botonVerMas" href="{% url 'producto-detalle' producto.id %}">Ver más</a>
          </div>
        {% endfor %}
      </section>
    </main>
    <footer class="footer">
      <p>Copyright &copy; 2023</p>
    </footer>
  </div>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="icon" href="{% static 'img\logo_main.png' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Iniciar Sesión</title>
</head>
<body>
    <header>
        <div class="buttons">
          <a href="{% url 'index' %}" class="btn">Inicio</a>
          <a href="{% url 'profesionales' %}" class="btn">Profesionales</a>
          <a href="{% url 'no_profesionales' %}" class="btn">Estandar</a>
        </div>
    </header>
    <h2>Iniciar Sesión</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="botonVerMas" type="submit">Iniciar Sesión</button>
        <a href="{% url 'registro' %}" class="btn-register">Registrarse</a>
    </form>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/no_profesional.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="icon" href="{% static 'img\logo_main.png' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Productos</title>
</head>
<body>
    <header>
        <div class="buttons">
          <a href="{% url 'index' %}" class="btn">Inicio</a>
          <a href="{% url 'profesionales' %}" class="btn">Profesionales</a>
          {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}" class="btn">Perfil</a>
          {% else %}
              <a href="{% url 'login' %}" class="btn">Iniciar Sesión o Registrarse</a>
          {% endif %}
        </div>
        <div class="cart-icon" style="position: absolute; top: 10px; right: 40px;">
            <a href="{% url 'ver_carrito' %}" id="cart-link">
              <img href="{% url 'ver_carrito' %}" src="{% static 'img/bolsa_compras.png' %}" alt="Carrito">
              <span id="cart-count">12</span>
            </a>
        </div>
    </header>
    <main class="container">
        <h2>Auriculares Estandar</h2>
        <div class="products">
            {% for producto in productos %}
                <div class="product">
                    <img src="{{ producto.get_imagen_url }}" alt="{{ producto.nombre }}">
                    <h3>{{ producto.nombre }}</h3>
                    <p>Precio: ${{ producto.precio }}</p>
                    <a class="botonVerMas" href="{% url 'producto-detalle' producto.id %}">Ver más</a>
                </div>
            {% endfor %}
        </div>
    </main>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/perfil.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Perfil de Usuario</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'img\logo_main.png' %}">
</head>
<body>
    <header>
        <div class="buttons">
          <a href="{% url 'index' %}" class="btn">Inicio</a>
          <a href="{% url 'profesionales' %}" class="btn">Profesionales</a>
          <a href="{% url 'no_profesionales' %}" class="btn">Estandar</a>
        </div>
    </header>
    <div class="container">
        <h2>Perfil de Usuario</h2>
        <p>Bienvenido, {{ usuario.username }}</p>
        <p>Correo electrónico: {{ usuario.email }}</p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="botonVerMas">Cerrar sesión</button>
        </form>
        {% if productos_en_carrito %}
            <h2>Productos en tu carrito:</h2>
        <ul>
        {% for producto in productos_en_carrito %}
            <li>{{ producto.nombre }} - Precio: {{ producto.precio }}</li>
         <!-- Otros detalles del producto -->
            {% endfor %}
        </ul>
        {% else %}
            <p>No hay productos en tu carrito.</p>
        {% endif %}     
    </div>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/producto_detalle.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script defer src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script defer src="{% static 'js/script.js' %}"></script>
  <link rel="icon" href="{% static 'img\logo_main.png' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/producto_detalle.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <title>Detalles del producto - {{ producto.nombre }}</title>
</head>
<body>
  <div class="container">
    <main class="product-details">
      <div class="container">
        <header class="header-product-details">
          <div class="logo">
            <a href="{% url 'index' %}">
              <img src="{% static 'img\logo_main.png' %}" alt="Logo">
            </a>
          </div>
          <div class="product-header">
            
          <nav>
            <ul>
              <a href="{% url 'index' %}" class="botonVerMas">Inicio</a>
              <a href="{% url 'profesionales' %}" class="botonVerMas">Profesionales</a>
              <a href="{% url 'no_profesionales' %}" class="botonVerMas">Estandar</a>
              {% if user.is_authenticated %}
                <li><a href="{% url 'perfil' %}" class="botonVerMas">Perfil</a></li>
              {% else %}
                <li><a href="{% url 'login' %}" class="botonVerMas">Login</a></li>
              {% endif %}
            </ul>
          </nav>
            <h1>Detalles - {{ producto.nombre }}</h1>
          <div class="cart-icon" style="position: absolute; top: 100px; right: 40px;">
            <a href="{% url 'ver_carrito' %}" id="cart-link">
              <img href="{% url 'ver_carrito' %}" src="{% static 'img/bolsa_compras.png' %}" alt="Carrito">
              <span id="cart-count">12</span>
            </a>
        </div>
        </div>
        </header>
        <main class="product-details">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              {% for imagen in imagenes %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                  <img class="d-block" src="{{ imagen.imagen.url }}" alt="Imagen del producto" style="width: 450PX; height: auto;">
                </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </a>
          </div>
          <div class="product-info">
            <h2>{{ producto.nombre }}</h2>
            <p class="price">Precio: ${{ producto.precio }}</p>
            <p class="category">Categoría: {{ producto.get_categoria_display }}</p>
            <p class="description">Descripción: {{ producto.descripcion }}</p>
            <form method="post">
              {% csrf_token %}
              <button class="add-to-cart" id="add-to-cart-btn"" type="submit">Agregar al carrito</button>
            </form>
          </div>
        </main>
        <footer>
          <p>&copy; 2023</p>
        </footer>
      </div>
  </div>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/profesional.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="icon" href="{% static 'img\logo_main.png' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Productos</title>
</head>
<body>
    <header>
        <div class="buttons">
            <a href="{% url 'index' %}" class="btn">Inicio</a>
            <a href="{% url 'no_profesionales' %}" class="btn">Estandar</a>
            {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}" class="btn">Perfil</a>
            {% else %}
              <a href="{% url 'login' %}" class="btn">Iniciar Sesión o Registrarse</a>
            {% endif %}
        </div>
        <div class="cart-icon" style="position: absolute; top: 10px; right: 40px;">
            <a href="{% url 'ver_carrito' %}" id="cart-link">
              <img href="{% url 'ver_carrito' %}" src="{% static 'img/bolsa_compras.png' %}" alt="Carrito">
              <span id="cart-count">12</span>
            </a>
        </div>
    </header>
    <main class="container">
        <h2>Auriculares Profesionales</h2>
        <div class="products">
            {% for producto in productos %}
                <div class="product">
                    <img src="{{ producto.get_imagen_url }}" alt="{{ producto.nombre }}">
                    <h3>{{ producto.nombre }}</h3>
                    <p>Precio: ${{ producto.precio }}</p>
                    <a class="botonVerMas" href="{% url 'producto-detalle' producto.id %}">Ver más</a>
                </div>
            {% endfor %}
        </div>
    </main>
</body>
</html>

Parcial_Final/Appportal/Webinicio/templates/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>    
    <link rel="icon" href="{% static 'img\logo_main.png' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}">
    <title>Registro</title>
</head>
<body>
    <div class="buttons">
        <a href="{% url 'index' %}" class="btn">Inicio</a>
        <a href="{% url 'profesionales' %}" class="btn">Profesionales</a>
        <a href="{% url 'no_profesionales' %}" class="btn">Estandar</a>
      </div>
    </header>
    <h2>Registro</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="botonVerMas" type="submit">Registrarse</button>
        <a href="{% url 'login' %}" >Iniciar Sesión</a>
    </form>
</body>
</html>